// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { parse } from 'yaml';

// One site for every Open Citadel standard.
//
//   /            what Open Citadel is
//   /oars/       the Open App Risk Standard
//   /community/  charter, governance, code of conduct
//
// Content is generated by scripts/sync-content.mjs from the submodules under
// vendor/, so the site cannot drift from the standards it publishes.

// The sidebar is built from the standard's own section list rather than being
// hand-maintained here, so adding a section to the spec adds it to the nav.
const spec = parse(readFileSync('./vendor/oars/standard/spec.yaml', 'utf8'));

const oarsSections = spec.sections.map((section) => ({
  label: `${Number(section.id)}. ${section.title}`,
  link: `/oars/${section.file.replace(/\.md$/, '')}/`,
}));

export default defineConfig({
  site: 'https://open-citadel.org',
  integrations: [
    starlight({
      title: 'Open Citadel',
      description:
        'Open standards for Microsoft security decisions. OARS — the Open App Risk Standard — ' +
        'rates the risk of applications and the permissions they request in Microsoft Entra ID.',
      // The concept mark from opencitadel/citadel-design (status: concept, not
      // an approved production vector). Cropped and resized only.
      logo: { src: './src/assets/citadel-icon.png', alt: '' },
      favicon: '/favicon.png',
      head: [
        {
          tag: 'link',
          attrs: { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:site_name', content: 'Open Citadel' },
        },
      ],
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/opencitadel' },
        { icon: 'discord', label: 'Discord', href: 'https://open-citadel.org/discord' },
      ],
      lastUpdated: true,
      customCss: ['./src/styles/citadel.css'],
      // Dark code blocks in both modes, platform-docs style.
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: { borderRadius: '0.75rem' },
      },
      // Two groups, one per repository the site renders. A third standard adds
      // a third group; nothing else should.
      sidebar: [
        {
          label: 'OARS',
          items: [
            { label: 'The standard', link: '/oars/' },
            ...oarsSections,
            { label: 'Permissions', link: '/oars/permissions/' },
            { label: 'Open questions', link: '/oars/open-questions/' },
            { label: 'Contributing', link: '/oars/contributing/' },
          ],
        },
        {
          label: 'Community',
          items: [{ autogenerate: { directory: 'community' } }],
        },
      ],
      components: {
        Footer: './src/components/Footer.astro',
        ThemeSelect: './src/components/ThemeSelect.astro',
      },
    }),
  ],
});
