#!/usr/bin/env node
// Verifies every internal link in the built site resolves to a real page or asset.
//
// The failure this exists to catch: a specification section is renamed in the
// OARS repository, and every cross-reference to it silently becomes a 404. The
// markdown still looks fine in review, so only a built-output check finds it.

import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

if (!existsSync(DIST)) {
  console.error('\n  dist/ does not exist. Run `npm run build` first.\n');
  process.exit(1);
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) walk(path, out);
    else if (entry.endsWith('.html')) out.push(path);
  }
  return out;
}

// Generated by the bundler and the search index; not ours to verify.
const IGNORED_PREFIXES = ['/_astro', '/pagefind'];
const ASSET = /\.(json|xml|svg|png|jpg|jpeg|ico|css|js|txt|webmanifest)$/;

const pages = walk(DIST);
const broken = [];

for (const file of pages) {
  const from = '/' + file.slice(DIST.length + 1).replace(/index\.html$/, '');
  const html = readFileSync(file, 'utf8');

  for (const match of html.matchAll(/(?:href|src)="(\/[^"#?]*)/g)) {
    const href = match[1];
    if (IGNORED_PREFIXES.some((p) => href.startsWith(p))) continue;

    const resolves = ASSET.test(href)
      ? existsSync(join(DIST, href))
      : existsSync(join(DIST, href, 'index.html')) ||
        existsSync(join(DIST, href.replace(/\/$/, '') + '.html'));

    if (!resolves) broken.push({ from, href });
  }
}

console.log('');
if (broken.length === 0) {
  console.log(`  ✓ ${pages.length} pages, no broken internal links`);
  console.log('');
  process.exit(0);
}

console.log(`  ✗ ${broken.length} broken internal link${broken.length > 1 ? 's' : ''}:`);
console.log('');
const grouped = new Map();
for (const { from, href } of broken) {
  if (!grouped.has(from)) grouped.set(from, new Set());
  grouped.get(from).add(href);
}
for (const [from, hrefs] of grouped) {
  console.log(`  ${from}`);
  for (const href of hrefs) console.log(`      → ${href}`);
}
console.log('');
process.exit(1);
